timvideos/litex-buildenv

- targets/arty/base.py
- targets/nexys_video/base.py
Changes to: 
* ddr3 read leveling parameters for arty and nexys_video
* reset signal polarity on arty
> arty/base and nexys_video/base: Fix ddr3 and reset

- scripts/build-micropython.sh
Updated git repo URL for micropython.git; re-enabled building of combined
micropython.bin as it is useful on Nuamto Mimas v2.  Tested with lm32
soft CPU; appears not to work with or1k soft CPU at this time ("system.h
not found")
> build-micropython.sh: new URL, build micropython.bin

- Makefile
- scripts/build-qemu.sh
- Set --group for atftpd (the default group it uses doesn't exist on arch)
- Use `ip` instead of `ifconfig` if not available
> Make qemu script work on Arch

- Makefile
Updates litex submodule pin to include [Alternate TFTP Server Port BIOS support](https://github.com/enjoy-digital/litex/pull/52), where if BIOS is built with TFTP_SERVER_PORT set then it will try TFTP from that port first before falling back to UDP/69.
Update Makefile to start TFTP server on port specified in TFTP_SERVER_PORT if set (defaulting to UDP/69).  If TFTP_SERVER_PORT is >= 1024 then TFTP server is started as user, without using sudo; otherwise TFTP server is started via sudo as before.
`atftpd` path tested; `in.tftpd` path written but not tested.
(Writing this change overlapped with merging of another change around TFTP group, so I've ended up rebase/squashing it into a single commit, but I think I've kept the sense of the overlapping change; I had to do the same thing to be …
> TFTP: Support alternate TFTP Server Port

- targets/arty/Makefile.mk
Copied over "make firmware-load" target from `mimasv2/Makefile.mk` so that firmware is not hard coded to be H2U firmware, but instead depends on `F=....` value.
> arty: Support "make firmware-load" for F=micropython

- Makefile
- firmware/hdmi_in.sh
- firmware/version_data.sh
- scripts/build-linux.sh
- scripts/build-qemu.sh
Bunch of fixes both extracted from @jimmo temporary commits and added while getting LiteEth to boot in QEMU for @shenki.
Fixes #14.
> Random collection of fixes.

- Makefile
Make litex-submodules also check if submodules are "current" (ie,
match the sha1 indicated in the parent repository -- timvideos/litex-buildenv)
and if not, emit a warning that they are out of date.
Produces a warning like:
<pre>
***************************************************************************
WARNING: the following submodules do not match expected commit:
+dcbe02b33c7b898fe8b768e5d3aaac2e257ce728 third_party/litex (timvideos-2018-01-14-31-gdcbe02b)
If you are not developing in submodules you may need to run:
git submodule update --init --recursive
manually to bring everything back in sync with upstream
***************************************************************************
</pre>
NOTE: we do _not_ force update in the Makefile, as this would make it
difficult to test …
> Makefile: check if submodules are current, warn if not

- Makefile
Rework tftpd detection logic to use immediate Makefile assignment,
and "check for empty" instead of "check for not assigned".  Thanks
to @stffrdhrn for pointing this out:
https://github.com/timvideos/litex-buildenv/pull/16/files#r162814028
> Makefile: tftpd: fix detection logic

- Makefile
This fixes the most obvious issue with running `in.tftpd` as a non-root user, by getting the syntax for the listening port correct.  Unfortunately at least when run on Ubuntu 16.04 the next result is:
Feb  7 11:39:20 parthenon in.tftpd[1690]: cannot set groups for user ewen
Feb  7 11:39:22 parthenon in.tftpd[1691]: cannot set groups for user ewen
Feb  7 11:39:25 parthenon in.tftpd[1694]: cannot set groups for user ewen
Feb  7 11:39:27 parthenon in.tftpd[1695]: cannot set groups for user ewen
Feb  7 11:39:30 parthenon in.tftpd[1699]: cannot set groups for user ewen
(one for each TFTP REQ attempt).  I've found references to that going back 10 years, so I'm not 100% sure it will be possible to run `in.tftpd` as a non-`root` non-`nobody` (default user it changes to) user.  Needs more …
> tftpd: Fix in.tftpd alternate port syntax

- Makefile
- targets/mimasv2/Makefile.mk
If `FIRMWARE=none ` then the firmware will be omitted in `make image-flash`, but previously it would still try to build a `none.fbi` firmware image to include.  Move `.fbi` dependency into a variable so that we can replace it with a blank string if `FIRMWARE=none`.  Appears to work as expected for both `FIRMWARE=micropython` and `FIRMWARE=none`.
> Makefile: make FIRMWARE=none work, Mimas v2 gateware-flash redirected to include BIOS

- Makefile
- scripts/enter-env.sh
Two misc fixes:
- to remove errors when in.tftpd is not installed, and
- prepend to PROMPT_COMMAND, rather than overwriting its contents.
> Fixes to PROMPT_COMMAND

- scripts/build-micropython.sh
Update `scripts/build-micropython.sh` to match new directory layout in [updated FuPy MicroPython](https://github.com/fupy/micropython/pull/16) (updated as per https://github.com/fupy/micropython/pull/16).
> scripts/build-micropython.sh: New MicroPython directory layout

- .gitmodules
Third party submodule updates, `cherry-pick`ed from https://github.com/timvideos/litex-buildenv/pull/34, so that they can be merged separately from the other changes.
This includes a URL change of `third_party/edid-decode` which means it is extra difficult to update a git repo which already has that submodule checked out, because the git repo at the old location and the git repo at the new location do not match.
Most reliable "reset" without giving up and cloning everything again seems to be:
rm -rf .git/modules/third_party/edid-decode third_party/edid-decode && git submodules sync && git submodules update --init --recursive
which just forces cloning `edid-decode` again without any reference to the old history.
Without doing this, things like "`git push`" will fail with the error:
The …
> Update third party submodules (including edid-decode)

- Makefile
With this change we can build `CPU=lm32` `CPU_VARIANT=minimal`, and boot MicroPython on the Mimas V2 and the Arty.  It appears with the `-Ot cpu_variant minimal` the firmware does not get built in the right directory, which causes building MicroPython to fail (and possibly other things).
Boot on the Mimas V2 is *very* slow with this variant (possibly several timeouts).  Boot on the Arty seems relatively quick.  I've not attempted to debug the cause of this, but this trivial fix appears necessary for `CPU_VARIANT=minimal` to build.
> Makefile: pass CPU_VARIANT through to firmware build

- flash.py
- make.py
- mkimage.py
Means the larger BIOS size on or1k should be understood by `mkimage.py`
command.
Fixes #43.
> tools: Read the BIOS maxsize from the SoC.

- make.py
Fixes;
```
AttributeError: 'Namespace' object has no attribute 'integrated_rom_size'
```
> make: Fix missing arguments issue.

- scripts/build-qemu.sh
The arg available to specify serial for -drive was to be used for
specifying a drive serial number.  However, we we using it to specify
the flash driver.  This was a hack.
Introduce a driver option to be able to specify this on litex_ssi.  This
will then be read during ssi bus / drive initialization to initialize
the requested guest hardware.
By default we fall back to m25p80.
Example usage:
-drive if=mtd,format=qcow2,file=build/arty_net_or1k//qemu.qcow2
-global litex_ssi.spiflash=mx25l1606e
This depends on qemu patches to be used, over at: 
https://github.com/stffrdhrn/qemu/tree/litex
If the patches are not available it the argument will just be ignored.
> qemu: Fix spiflash args as per deprecated args

- .travis.yml
- .travis/build.sh
- .travis/run.inc.sh
- .travis/setup.sh
- Makefile
- firmware/Makefile
- firmware/stub/Makefile
- scripts/build-linux.sh
- scripts/download-env.sh
- scripts/enter-env.sh
- scripts/settings.sh
- targets/arty/net.py
- targets/atlys/net.py
- targets/nexys_video/net.py
- targets/opsis/base.py
- targets/opsis/net.py
- targets/sim/net.py
Currently or1k is stuff on 5.4.0, but the lm32 and riscv32 should both
work with gcc 8.2.0
> scripts: Move the GCC toolchain to 8.2.0

- targets/tinyfpga_bx/base.py
Ignore the first two commits: they'll already be in master by the time you get to this, but I wanted to add the following changes:
* Add the `cas` module to control the LED.
* Disable reset pin, b/c it's finicky unless you tie it to ground and it'll probably confuse most people. Let's prefer a reset to the bootloader image instead.
> Final Touches On TinyFPGA Platform

- scripts/build-micropython.sh
Partial attempt at getting `litex-buildenv` to build on `or1k` per https://github.com/fupy/micropython/issues/3.  This copies in `system.h`, `csr-defs.h` and `spr-defs.h` into `build` `software/include` directory so they can be included.
Currently still does not build, as there still issues with things being redefined:
<pre>
In file included from ../../py/mpprint.c:33:0:
../../py/mphal.h:46:6: error: conflicting types for 'mp_hal_stdout_tx_strn'
void mp_hal_stdout_tx_strn(const char *str, size_t len);
^
In file included from ../../py/mphal.h:34:0,
from ../../py/mpprint.c:33:
./mphalport.h:13:20: note: previous definition of 'mp_hal_stdout_tx_strn' was here
static inline void mp_hal_stdout_tx_strn(const char *str, mp_uint_t len) {
^
../../py/mkrules.mk:47: recipe for target …
> Copy litex's libbase files into the micropython include path

- .travis.yml
- platforms/ice40_hx8k_b_evn.py
- targets/ice40_hx8k_b_evn/Makefile.mk
- targets/ice40_hx8k_b_evn/base.py
This PR adds `litex-buildenv` and `micropython` support to Lattice's [ice40-HX8K Breakout Board](https://www.latticesemi.com/Products/DevelopmentBoardsAndKits/iCE40HX8KBreakoutBoard.aspx). This should be merged after Litex [#112](https://github.com/enjoy-digital/litex/pull/112) has been merged.
> Add ICE40HX8K-B-EVN Platform

- .travis.yml
- gateware/up5kspram.py
- platforms/ice40_up5k_b_evn.py
- targets/ice40_up5k_b_evn/Makefile.mk
- targets/ice40_up5k_b_evn/base.py
- targets/ice40_up5k_b_evn/bridge.py
This PR adds preliminary support for ICE40 UltraPlus Family members with 5280 LUTs. The design is a tight fit, even with the `minimal` variant (and this is _without_ features like `ControlAndStatus` or `spi`/`i2c`). 
Both the `minimal` and `lite` variants of the `lm32` CPU are tested pending further optimizations; I _really_ want the cache of the `lite` variant, but it might not be possible to reduce resource usage much further.
Currently TODO:
* RGB LEDs (using the built-in primitive?)
* _Possibly_ SPI/I2C IP (using the built-in cores?)?
> ICE40UP5K-B-EVN Support

- .travis.yml
- platforms/icebreaker.py
- targets/icebreaker/Makefile.mk
- targets/icebreaker/base.py
Self-explanatory PR. Tested with lm32 in the `minimal` variant. LEDs work :).
> platforms: Add icebreaker platform with base target. Micropython boots.

- platforms/tinyfpga_bx.py
- targets/tinyfpga_bx/base.py
* Remove duplicate entry in `targets/tinyfpga_bx.py`.
* Add useful comments.
> tinyfpga_bx: Actually use pins documented.

- scripts/enter-env.sh
Change "exit 1" to "return 1" as this script is sourced (therefore running in the same shell).
Check if the script is sourced from bash (as it uses bash-specific features).
> Fixes in enter-env.sh script.

- scripts/download-env.sh
Self-explanatory, according to [pip docs](https://pip.readthedocs.io/en/stable/reference/pip_install/#vcs-support), this is the correct way to use pip to install directly from a repository.
Tested locally on my machine and it worked just fine.
> Install tinyprog from repo until new version is uploaded to PyPI.

- scripts/build-zephyr.sh
- scripts/download-env.sh
- scripts/enter-env.sh
- scripts/settings.sh
This adds a script for building Zephyr RTOS for VexRiscv as a firmware for LiteX Buildenv.
> scripts: Add build-zephyr.sh script.

- scripts/build-zephyr.sh
In the PR I changed the board name from `arty_litex_vexriscv` to `litex_vexriscv`. Without this fix, the script will fail when building Zephyr.
> zephyr: Change LiteX+VexRiscv board name

- scripts/build-common.sh
- scripts/build-qemu.sh
- scripts/build-renode.sh
- scripts/generate-renode-scripts.py
This adds support for running LiteX in Renode emulation framework.
> scripts: Add Renode emulation support.

- scripts/build-renode.sh
This eliminates the requirement of mono environment
installed in the system.
> scripts: switch to portable Renode release

- scripts/build-renode.sh
Without this fix, `RENODE_BIN` is empty and the script fails.
> scripts: fix running portable Renode

- firmware/uip/contiki-conf.h
- targets/arty/net.py
- targets/atlys/net.py
- targets/mimas_a7/net.py
- targets/nexys_video/net.py
- targets/opsis/net.py
- targets/sim/net.py
This PR fixes two problems with endianness for little endian CPUs (like VexRiscv):
* liteeth was configured to big endian and it was not possible to netboot in LiteX bios on VexRiscv,
* uip was configured to big endian and it was not possible to telnet into the firmware on VexRiscv.
> Fix endianness

- scripts/build-qemu.sh
Resolve a compile error on Debian Sid.
GCC - 8.3.0-19
libglusterfs - 6.4-2
```
error e.g.
/home/daves/github/litex-buildenv/third_party/qemu-litex/block/gluster.c:1038:13: error: too few arguments to function ‘glfs_ftruncate’
if (glfs_ftruncate(fd, offset)) {
```
> Exclude glusterfs from qemu build

- .travis.yml
- Makefile
- scripts/build-linux.sh
- targets/arty/base.py
- targets/opsis/base.py
This PR updates submodules with the newest version of:
* `VexRiscv` supporting building emulator (BIOS) for LiteX target,
* `LiteX` 
* with the fixed netboot/flashboot for VexRiscv.linux cpu,
* with cpu variant information generated to `csr.csv`,
* `litex-renode` with the enhancements in script generating Renode platform utilizing new information in `csr.csv` and supporting more peripherals
It also adds generation of `emulator_ram` to arty target when building for `VexRiscv.linux` cpu. This is a memory where VexRiscv emulator is loaded by the LiteX BIOS.
**EDIT**: I split this PR into 3 separate ones. This one contains now changes related to building Linux for VexRiscv using `./scripts/build-linux.sh` script.
> Better vexriscv linux support

- .travis/fixup-git.sh
* Always build, no longer fail.
* Work out the actual commit checked out by travis verse `TRAVIS_COMMIT`.
* Compare upstream pull request value to both `TRAVIS_COMMIT` and checked out by travis.
> travis: Change way fixup-git works.

- scripts/build-linux.sh
These packages are now available via conda since;
* https://github.com/litex-hub/litex-conda/pull/75
* https://github.com/litex-hub/litex-conda/pull/80
> scripts: Use Linux MUSL toolchain for building Linux Kernel.

- targets/tinyfpga_bx/Makefile.mk
Closes #191 Need to update docs to export PROG_PORT on WSL
> tinyfpga-bx: Add prog-port to Makefile

- README.md
- scripts/debian-setup.sh
* Remove dependencies no longer needed from `scripts/debian-setup.sh`.
* Update the README documentation to remove references to `scripts/download-env-root.sh`.
> Small README fixes

- .travis.yml
- platforms/icefun.py
- scripts/download-env.sh
- scripts/enter-env.sh
- targets/icefun/Makefile.mk
- targets/icefun/base.py
Tracking the initial porting of IceFun board, See #181 
Platform and targets based on ice40_hx8k_b_evnboard 
I've moved the rest of the todos to issue #181, I'll follow up later with another PR for the rest, but I'd like to get this mainlined.
> iceFUN board

- scripts/download-env.sh
- scripts/enter-env.sh
* Fixes conda package name (nextpnr -> nextpnr-ice40).
* Detect if iCE40 or ECP5 toolchain is needed.
> scripts: Support both iCE40 and ECP5 toolchains.

- scripts/download-env.sh
- scripts/enter-env.sh
Commit 63e30284a257de04848869cb1cbd1ca5f6c55c9d
Date:   2019-05-03 19:39:22 -0700
>      * Rename `download-env-root.sh` to `debian-setup.sh` (should stop
>        people thinking we are Debian only).
File was renamed but old name appears in scripts (one real, one in a commented-out section).
This PR fixes.
> Complete the renaming of download-env-root.sh to debian-setup.sh.

- scripts/build-micropython.sh
Image is not required in all cases, e.g.,
when simulating in Renode or loading
firmware/gateware directly to RAM.
> micropython: allow to skip building image

- scripts/build-renode.sh
This PR changes the way Renode is started by the `./scripts/build-renode.sh` script.
Instead of just passing a generated `resc` script to Renode, a series of `-e` switches is used. It allows user to pass own additional arguments before starting the simulation.
*Note:* currently the generated script contains a `start` command at the end so the last `-e s` is not necessary, but once this PR is merged I will remove the final `start` from the generator. Proceeding in this order is to ensure that this script works during the transition period.
> Allow to pass additional arguments to Renode

- scripts/build-linux.sh
- scripts/build-renode.sh
- scripts/download-env.sh
- scripts/enter-env.sh
This is an introductory PR for conda-pack support. It does 3 things:
- fixes verification of gcc installation
- moves Renode to use conda instead of regular packages
- adds CONDA_PREFIX variable (required for Renode)
> Use Renode from Conda

- scripts/download-env.sh
- scripts/enter-env.sh
- targets/mimasv2/Makefile.mk
Currently all scripts use local copy of MimasV2 config tool obtained by wget. This PR use python package to deliver this tool, which allows it to be used as python module.
This should me merged as soon as PR: https://github.com/numato/samplecode/pull/45 is merged.
After that old method of providing the tool will fail.
> [FIX] scripts: Use python package for MimasV2Config

- scripts/build-linux.sh
- scripts/build-renode.sh
- targets/arty/base.py
- targets/atlys/base.py
- targets/ice40_hx8k_b_evn/base.py
- targets/ice40_up5k_b_evn/base.py
- targets/icebreaker/base.py
- targets/icefun/base.py
- targets/mimasv2/base.py
- targets/minispartan6/base.py
- targets/opsis/base.py
- targets/pipistrello/base.py
- targets/sim/base.py
- targets/tinyfpga_bx/base.py
- targets/upduino_v1/base.py
This PR contains separate (unrelated) commits:
* remove an obsolete and possibly misleading comment (minor fix);
* restore generation of `flash_boot_address` constant;
It's required by Renode to load firmware binary to a proper offset in flash. It has been previously generated by `litex`, but it is no more after bumping to the newest version.
* use proper path to conda-provided Renode
> Renode fixes

- .travis.yml
- platforms/pano_logic_g2.py
- targets/pano_logic_g2/Makefile.mk
- targets/pano_logic_g2/base.py
Aim of this PR is to add initial support for [Pano Logic Zero Client G2](https://github.com/tomverbeure/panologic-g2).
Initial version supports only a basic set of features:
* UART exposed on DVI DDC pins
* Single DDR2 chip
With this configuration it is possible to run Linux built using `./scripts/build-linux.sh`, only catch is that it must be transferred over a serial connection.
Additionally I'm not sure how should I implement the `gateware-load` target and similar because the device has only a JTAG header and no built-in programmer
> platforms: add pano logic g2 platform

- .gitignore
- make.py
- scripts/build-linux.sh
Currently the script uses prebuilt rootfs and devicetree for VexRiscv configuration, this PR aims to add option to build Linux using Buildroot from [linux-on-litex-vexriscv](https://github.com/litex-hub/linux-on-litex-vexriscv).
This also fixes the issue with LiteX configuration not matching the prebuilt devicetree which for example surfaced in #223 where board has 64MiB of DRAM but devicetree specifies only 32MiB
By default the old method of building Linux is used, to use Buildroot first export `BUILD_BUILDROOT=1`
> scripts/build-linux.sh: add option to build rootfs and devicetree from scratch

- targets/arty/tf.py
Tf target is used with Zephyr Tensorflow lite demo. The target adds I2C master routed to PMOD D connector. This target is used by the Litex/Vexriscv TF lite Zephyr demo (https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo)
> targets: arty: add tf target

- platforms/waxwing.py
- targets/waxwing/net.py
Due to changes in litex (mainly due to initial values of integrated_rom_size and integrated_sram_size) I was not able to update to current master since that breaka all builds. So this contain update of litex only to version that contains my changes in ISE + Yosys flow.
Waxwing platform needed to be updated to reflect official port mapping from https://productdata.numato.com/assets/downloads/fpga/waxwing/developmentboard/WaxwingSpartan6DevelopmentBoardV3.ucf
Also added net configuration which makes ethernet work on board as well.
*NOTE:* part of code is disabled in net.py, but fix for that is available later in litex, so it can be enabled later.
To use Yosys with ISE flow just execute:
```MAKE_LITEX_EXTRA_CMDLINE="--build-option mode yosys" make gateware```
> Linux on Spartan6

- scripts/build-zephyr.sh
Make sure that `csr.csv` file is generated before using it to generate DTS overlay.
> build-zephyr: Generate csr.csv before DTS overlay

- .travis.yml
- platforms/matrix_voice.py
- targets/matrix_voice/Makefile.mk
- targets/matrix_voice/base.py
Adding basic support for MATRIX Voice (https://www.matrix.one/products/voice)
Support includes:  
* 75MHz system clock
* DDR2 (300MHz)
* UART to Raspberry Pi (230400 baud)
* GPIO connector (P2)
* 8MB SPI FLASH memory
* Debug LED
Passed tests:
* **PICORV32** and **VEXRISC** has been tested, 
* **micropython** was tested on both softcores,
*  **Zephyr** OS was tested on  **VEXRISC** lite.
> MATRIX Voice supported

- scripts/build-linux.sh
This is to make sure that rootfs, config and DTB are correct when building the linux image.
This fixes the problem reported in https://github.com/timvideos/litex-buildenv/issues/341.
Note: there is also another commit (unrelated) that fixes builds without buildroot.
> Verify checksums of downloaded files

- scripts/build-micropython.sh
This reverts commit 421a402a68824dda81395c58675c1d55c21a0261
as the current fupy/micropython no more contains the
problematic `hw` directory.
> micropython: use fupy/micropython fork

- scripts/build-renode.sh
- targets/arty/base.py
- targets/atlys/base.py
- targets/ice40_hx8k_b_evn/base.py
- targets/ice40_up5k_b_evn/base.py
- targets/icebreaker/base.py
- targets/icefun/base.py
- targets/mimasv2/base.py
- targets/minispartan6/base.py
- targets/opsis/base.py
- targets/pipistrello/base.py
- targets/sim/base.py
- targets/tinyfpga_bx/base.py
- targets/upduino_v1/base.py
- targets/utils.py
This PR adds the definition of flash layout for Linux binaries (required for the offsets to be included in the LiteX configuration `csr.csv` file) and modifies `scripts/build-renode.sh` script so it now loads them.
NOTE:  This requires https://github.com/litex-hub/litex-renode/pull/22 to merged first!
> Allow to boot Linux from flash

- targets/pano_logic_g2/base.py
(builds and runs BIOS, I haven't been able to get Linux to run yet)
> Add emulator_ram to fix CPU_VARIANT=linux build for pano_logic_g2.

- platforms/pano_logic_g2.py
Several Pano hackers use the DDC lines on the HDMI port for a serial connection rather than the DVI port.  This change allows the connection to be HDMI port to be used without code modifications.
> Pano: Add support for specifying alternate UART connection

- scripts/build-common.sh
- scripts/build-linux.sh
- scripts/build-micropython.sh
- scripts/build-zephyr.sh
- scripts/download-env.sh
- scripts/download-prebuilt.sh
- scripts/enter-env.sh
Original issues:
1. When scripts were run from an external Makefile they failed because make prints "make[1]: Leaving directory ..." so eval tired to run "make[1]" which of course failed.
2. build-linux.sh only worked on the first run because it attempts to apply patches to already patched sources.
> Fix errors when scripts are called by Makefile, apply patches only once.

- scripts/build-linux.sh
Recent commits to linux-on-litex-vexriscv for SMP broke Linux for the Pano Logic platform.  These changes allow the linux-on-litex-vexriscv and the buildroot repositories to be checked out from specific (known working) commits.  
If BD_COMMIT, LLV_COMMIT and BR2_EXTERNAL are not set in the environment then the script behavior is unchanged.
Allowing BR2_EXTERNAL to be specified in the environment makes it possible to use a customized buildroot configuration for a specific platform.  For example to enable DHCP on eth0.
See https://github.com/skiphansen/panog2_linux/blob/master/Makefile for an example of how this can be used.
> Optionally allow checkout commits and BR2_EXTERNAL to be specified.

- firmware/pattern.c
- targets/arty/zephyr_no_ddr.py
This PR adds an Arty target with no DDR. The system is Zephyr capable and can be used with Symbiflow (see: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1316)
Zephyr runs from blockram based memory.
> Zephyr Arty no DDR

- .travis/download-xilinx.sh
- scripts/download-env.sh
- scripts/enter-env.sh
This is necessary in order to source Xilinx settings
in automatically generated toolchain scripts.
> Set Xilinx gateware toolchain location

- scripts/download-env.sh
Submodules must be initialized and updated before installing
pythondata-software-compiler_rt and python-cpu.
> download-env: Fix the installation of some python modules

- Makefile
- scripts/build-linux.sh
This updates submodules (including the LiteX submodule) and restores the support for the external DT file for linux on mor1kx.
> linux: mor1kx: Add support for the external DT

- .gitmodules
- .travis.yml
- gateware/ice40.py
- platforms/fomu.py
- targets/fomu/Makefile.mk
- targets/fomu/base.py
The aim of this PR is to add support for Fomu.
Initial design uses the Foboot configuration/firmware which requires special handling because it needs a custom BIOS, due to that at this point it is necessary to first run `make foboot-bios` to build the replacement BIOS before building other targets like `gateware`
It is also required to manually patch foboot with `firmware/foboot/putchar-fix.patch`
> Add Fomu support
