timvideos/litex-buildenv

targets/arty/ddr3.py, targets/atlys/hdmi2usb.py, targets/atlys/video.py, targets/mimasv2/memtest.py, targets/netv2/video.py, targets/nexys_video/ddr3.py, targets/nexys_video/video.py, targets/opsis/memtest.py, targets/opsis/video.py, targets/opsis/video_out_debug.py, targets/sim/memtest.py
Fixes;
```
[WARNING] Please update LiteDRAMCrossbar.get_port's "cd" parameter to "clock_domain"
[WARNING] Please update LiteDRAMCrossbar.get_port's "dw" parameter to "data_width"
```
=> targets: Updating for liteDRAM changes.

README.md
No description needed, I'd say :)
=> readme: Fix broken link

scripts/download-prebuilt.sh
=> scripts: Improve download-prebuilt script.

README.md
=> LiteX readme

firmware/ci.c
Support different combinations of CR/NL as is now down in the litex bios.
=> Firmware CR-NL

gateware/cas.py, platforms/ice40_up5k_b_evn.py, targets/ice40_up5k_b_evn/base.py
This PR updates submodules to pull in UART FIFO improvements, adds RGB LED support to the `ControlAndStatus` module, and then adds the newly updated `ControlAndStatus` module to the ICE40UP5K-B-EVN `base` target.
Tested with `lm32.minimal` CPU variant.
=> Add RGB LED support to ICE40UP5K-B-EVN Target

scripts/download-env.sh
Patch conda to make expanduser return the `${CONDA_DIR}` rather than the user's home directory.
Fixes https://github.com/timvideos/litex-buildenv/issues/128
=> scripts: More aggressive patching of conda.

scripts/download-prebuilt.sh
=> Fix upstream repository detection.

.travis.yml, platforms/upduino_v1.py, targets/upduino_v1/Makefile.mk, targets/upduino_v1/base.py
Tested with micropython for vexriscv and lm32 lite.
=> platforms: add upduino_v1 platform

scripts/bootstrap.sh
Fix issues with debian detection mentioned in https://github.com/timvideos/litex-buildenv/issues/131
=> bootstrap: fix logic inversion in platform detection

scripts/bootstrap.sh
As noted in https://github.com/timvideos/litex-buildenv/issues/131
=> scripts : update bootstrap.sh to use new repo name

scripts/build-zephyr.sh, scripts/download-env.sh, scripts/enter-env.sh
This switches Zephyr repository for VexRiscv to mainline and installs additional python dependency for Zephyr West buildtool.
=> Fix zephyr script

scripts/generate-renode-scripts.py
This fixes formatting in files modified by PR #127, wrapping long lines to 80 characters.
=> scripts: wrap lines to 80 characters

Makefile, firmware/Makefile, firmware/stub/Makefile, firmware/uip/liteethmac-drv.c, targets/arty/net.py, targets/atlys/net.py, targets/atlys/video.py, targets/mimas_a7/net.py, targets/mimas_a7/video.py, targets/netv2/bridge_pcie.py, targets/netv2/bridge_uart.py, targets/netv2/pcie.py, targets/nexys_video/base.py, targets/nexys_video/net.py, targets/nexys_video/video.py, targets/opsis/base.py, targets/opsis/net.py, targets/opsis/video.py, targets/sim/net.py, targets/utils.py
This updates submodules to the newest version and fixes files broken in a process.
=> Bump submodules

scripts/download-env.sh, scripts/settings.sh
Until https://github.com/conda/conda/issues/8843 is fixed.
=> scripts: Use older version of conda.

.travis.yml, .travis/run.inc.sh, Makefile, scripts/build-linux.sh, scripts/build-qemu.sh, scripts/download-env.sh, scripts/enter-env.sh
Fixes https://github.com/timvideos/litex-buildenv/issues/155
=> Update CPU=or1k to CPU=mor1kx for upstream change.

Makefile, scripts/download-env.sh, scripts/enter-env.sh
* sync the git submodule URLs.
* Check the CPU value
* Cleanup the zephyr deps.
=> Small scripts cleanup

scripts/download-env.sh, scripts/enter-env.sh
to work outside litex-buildenv dir
=> scripts : fix download-env/enter-env platform detection

scripts/download-env.sh
Potentially fixes @ewenmcneill ran into in #99.
=> scripts: Always update conda to pinned version.

.gitmodules, .travis.yml, .travis/build.sh, .travis/fixup-git.sh, make.py, scripts/build-linux.sh, scripts/download-env.sh, scripts/enter-env.sh, scripts/settings.sh, targets/arty/base.py, targets/basys3/base.py, targets/cmod_a7/base.py, targets/ice40_hx8k_b_evn/base.py, targets/ice40_up5k_b_evn/base.py, targets/icebreaker/base.py, targets/icefun/base.py, targets/mimas_a7/base.py, targets/mimas_a7/video.py, targets/mimasv2/base.py, targets/neso/base.py, targets/nexys_video/base.py, targets/nexys_video/video.py, targets/tinyfpga_bx/base.py, targets/upduino_v1/base.py
Updating submodules.
Core modules;
* migen changed from 0.6.dev-289-g5585912 to 0.6.dev-306-g41922fd
* litex changed from v0.1-1099-ge637aa65 to v0.1-1333-ga54b80b9
* litex-renode changed from b3fdb9b to 742360f
Peripherals;
* litedram changed from 6c53996 to 401554f
* liteeth changed from ad187d3 to 4d9e74f
* litepcie changed from 71c9a3a to 47e76f4
* litescope changed from 9e3b9d8 to 7a9fa9d
* litevideo changed from 98e145f to 49bafa4
Extras;
* edid-decode changed from 42f5fa4 to 3a6108a
* flash_proxies changed from 1c21ee4 to 01d8f81
=> Updating submodules.

.travis/add-local-submodule-inner.sh, .travis/add-local-submodules.sh, .travis/fixup-git.sh
```
Fetching submodule litex/soc/cores/cpu/minerva/verilog
fatal: remote error: upload-pack: not our ref 297db8adfed0671afd6114f8ff3c18c9434e4686s/master
The command "$PWD/.travis/setup.sh" failed and exited with 1 during .
```
=> Improvements to local git submodule script.

.travis.yml, scripts/download-env.sh, scripts/enter-env.sh
=> zephyr: Add missing `packaging` dependency

mkimage.py, scripts/enter-env.sh, targets/ice40_hx8k_b_evn/base.py
=> Misc fixes

targets/arty/tf.py
This PR adds missing import to Arty TF target
=> Fix Arty TF target

.travis.yml, .travis/build.sh, scripts/build-linux.sh, scripts/download-env.sh, scripts/enter-env.sh, scripts/test-renode.sh, targets/arty/base.py, targets/atlys/base.py, targets/mimas_a7/base.py, targets/netv2/base.py, targets/opsis/base.py, targets/pano_logic_g2/base.py, targets/pipistrello/base.py, targets/saturn/base.py, targets/waxwing/net.py, tests/renode/BIOS.robot, tests/renode/Firmware-firmware.robot, tests/renode/Firmware-linux.robot, tests/renode/Firmware-micropython.robot, tests/renode/Firmware-zephyr.robot, tests/renode/README.md
This PR adds Renode integration to Travis CI tests.
It includes basic test suits for:
* LiteX BIOS
* the default H2U firmware
* Zephyr
* micropython
* Linux
=> Testing firmware in Renode on Travis
